#!/usr/bin/env bash
#
# Adapted version of the following
# https://github.com/rumpkernel/rumprun-packages/blob/master/erlang/erlrun.sh
#

script_dir="$(dirname "$(readlink -f "$0")")"

show_help() {
cat << EOF
Usage: "${0##*/}" [-h] ...

    -h|--help      display this help and exit
    --erlhome      Erlang Home. (Default: /tmp)
    --erlpath      Path to erlang installation. (Default: /opt/erlang)
    --ip           Which IP to configure this VM on. (Default 10.0.120.101)
    --gw           Which gateway to configure this VM on. (Default 10.0.120.100)
    --virt         virtualization. One of xen, qemu, kvm
    --epmd         Enable Epmd. Requires the following options:
    --cookie       Set a specific cookie. (Default: mycookie)
    --name         Set a different name. (Default: rumprun)
    --dbname       Set database name. (Default: postgres_db)
    --dbuser       Set database username. (Default: postgres)
    --dbpass       Set database password. (Default: postgres)
    --dbhost       Set database hostname. (Default: 10.0.120.100)
    --dbport       Set database port. (Default: 5432)
    --iso          Set an iso filename.

EOF
}

main() {
  local erlhome=/tmp
  local erlpath=/opt/erlang
  local name=rumprun
  local ip=10.0.120.101
  local gw=10.0.120.100
  local cookie=mycookie
  local virt=qemu
  local epmd_opt=-no_epmd
  local epmd_conf=
  local dbname=postgres_db
  local dbuser=postgres
  local dbpass=postgres
  local dbhost=10.0.120.100
  local dbport=5432
  local iso=

  local OPTIND=1 # Reset is necessary if getopts was used previously
  while getopts "h-:" opt; do
    case "$opt" in
      h) show_help
        exit 0
        ;;
      -)
        case "$OPTARG" in
          erlhome=*)     erlhome="${OPTARG#*=}"     ;;
          erlpath=*)     erlpath="${OPTARG#*=}"     ;;
          ip=*)          ip="${OPTARG#*=}"          ;;
          gw=*)          gw="${OPTARG#*=}"          ;;
          virt=*)        virt="${OPTARG#*=}"        ;;
          epmd)          epmd_opt=''                ;;
          cookie=*)      cookie="${OPTARG#*=}"      ;;
          name=*)        name="${OPTARG#*=}"        ;;
          dbname=*)      dbname="${OPTARG#*=}"      ;;
          dbuser=*)      dbuser="${OPTARG#*=}"      ;;
          dbpass=*)      dbpass="${OPTARG#*=}"      ;;
          dbhost=*)      dbhost="${OPTARG#*=}"      ;;
          dbport=*)      dbport="${OPTARG#*=}"      ;;
          iso=*)         iso="${OPTARG#*=}"         ;;
          *) show_help
            exit 1
          ;;
        esac;;
      *) show_help
        exit 1
        ;;
    esac
  done

  if [[ -z "$iso" ]];
  then
    echo "Missing mandatory option --iso"
    exit 1
  fi

  [[ -z "$epmd_opt" ]] && {
    epmd_conf="-s erlpmd_ctl start -s setnodename start $name@$ip $cookie"
  }

  # -e ERTS_LIB_DIR="$erlpath/lib/erlang/lib"

  # the .boot is automatically appended to -boot bootfile

  # use "-mode embedded" for initial loading of all the modules (non-default)
  rumprun "$virt" \
     -I if,vioif,'-net tap,script=no,ifname=tap0' \
     -W if,inet,static,"$ip/24","$gw" \
     -e ERL_INETRC="$erlpath/erl_inetrc" \
     -e SERVICE_HOSTNAME="$ip" \
     -e PORT="80" \
     -e RDS_DB_NAME="$dbname" \
     -e RDS_USERNAME="$dbuser" \
     -e RDS_PASSWORD="$dbpass" \
     -e RDS_HOSTNAME="$dbhost" \
     -e RDS_PORT="$dbport" \
     -b ${iso},"$erlpath" \
     -M 256 \
     -g '-serial file:serial.log -nographic -vga none' \
     -i build/rumprun-packages/erlang/beam.hw.bin \
       "-- $epmd_opt -root $erlpath/lib/erlang \
        -boot $erlpath/lib/erlang/releases/latest/start \
        -config $erlpath/lib/erlang/releases/latest/sys.config \
        -boot_var ERTS_LIB_DIR $erlpath/lib/erlang/lib \
        -progname erl -- \
        -home $erlhome -noshell -noinput \
        -mode embedded \
        $epmd_conf"
}

main "$@"
